name: Flipkart
services:
  mongodb:
    build: ./mongodb
    image: sudhakar20000/mongodb:v1
    container_name: mongodb
  catalogue:
    build: ./catalogue
    image: sudhakar20000/catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    image: sudhakar20000/frontend:v1
    container_name: frontend
    ports:
      - "80:80" 
    depends_on:
      - mongodb
      - catalogue
      - redis
      - user
networks:
  default:
    name: flipkart
    driver: bridge
    external: false

  